steps:
  # Build the container image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend:latest'
      - '.'
<truncated 1130 characters>
  - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
