/**
 * Bill Repository
 * Data access layer for bills and statements
 */

import { query } from '../lib/db';

export interface BillRow {
    id: string;
    user_id: string;
    instrument_id: string | null;
    name: string;
    amount: number;
    min_due_amount: number | null;
    due_date: Date;
    category: string;
    status: 'pending' | 'paid' | 'overdue';
    auto_generated: boolean;
    created_at: Date;
}

export class BillRepository {
    /**
     * Find instrument by user and card last 4
     */
    static async findInstrumentByLast4(userId: string, cardLast4: string): Promise<string | null> {
        const result = await query(
            `SELECT id FROM instruments 
             WHERE user_id = $1 
             AND card_last4 = $2 
             AND type = 'credit_card'
             LIMIT 1`,
            [userId, cardLast4]
        );
        return result.rows[0]?.id || null;
    }

    /**
     * Check if bill already exists for instrument and month
     */
    static async findExistingBill(
        userId: string,
        instrumentId: string | null,
        month: number,
        year: number
    ): Promise<string | null> {
        const result = await query(
            `SELECT id FROM bills 
             WHERE user_id = $1 
             AND instrument_id = $2 
             AND EXTRACT(MONTH FROM due_date) = $3
             AND EXTRACT(YEAR FROM due_date) = $4`,
            [userId, instrumentId, month, year]
        );
        return result.rows[0]?.id || null;
    }

    /**
     * Create a new bill
     */
    static async create(data: {
        userId: string;
        instrumentId?: string | null;
        name: string;
        amount: number;
        minDueAmount?: number | null;
        dueDate: Date;
        category: string;
        autoGenerated?: boolean;
    }): Promise<BillRow> {
        const result = await query(
            `INSERT INTO bills (
                user_id, instrument_id, name, amount, min_due_amount,
                due_date, category, status, auto_generated, created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8, NOW())
            RETURNING *`,
            [
                data.userId,
                data.instrumentId || null,
                data.name,
                data.amount,
                data.minDueAmount || null,
                data.dueDate,
                data.category,
                data.autoGenerated ?? true,
            ]
        );
        return result.rows[0];
    }

    /**
     * Get bills for user
     */
    static async findByUserId(userId: string, limit?: number): Promise<BillRow[]> {
        const result = await query(
            `SELECT * FROM bills 
             WHERE user_id = $1 
             ORDER BY due_date ASC
             ${limit ? `LIMIT ${limit}` : ''}`,
            [userId]
        );
        return result.rows;
    }

    /**
     * Update bill status
     */
    static async updateStatus(billId: string, userId: string, status: string): Promise<boolean> {
        const result = await query(
            `UPDATE bills SET status = $1, updated_at = NOW() 
             WHERE id = $2 AND user_id = $3`,
            [status, billId, userId]
        );
        return (result.rowCount ?? 0) > 0;
    }
    /**
     * Create a new bill payment record (generated from transaction aggregates)
     */
    static async createBillPayment(data: {
        instrumentId: string;
        billMonth: number;
        billYear: number;
        billAmount: number;
        billDate: Date;
        dueDate: Date;
        paymentStatus: 'pending' | 'paid' | 'overdue';
    }): Promise<void> {
        await query(
            `INSERT INTO bill_payments (
                instrument_id, bill_month, bill_year, bill_amount,
                bill_date, due_date, payment_status
            ) VALUES ($1, $2, $3, $4, $5, $6, $7)
            ON CONFLICT (instrument_id, bill_month, bill_year) DO NOTHING`,
            [
                data.instrumentId,
                data.billMonth,
                data.billYear,
                data.billAmount,
                data.billDate,
                data.dueDate,
                data.paymentStatus
            ]
        );
    }
}
